src/App.js
src/index.js

I am not 100% sure on why the errors were displaying, but Quinne and I are setting up the base components now, and this branch will allow us to continue with the base set up.

Add basic setup so no errors are showing

---

src/components/App.css
src/components/App.js
src/components/App.test.js

Movie and MoviesContainer files and directories created. This PR is to be sure the previous PR is functional with the new directories.

Create component directories and files

---

src/App.js
src/containers/Movie/Movie.js
src/containers/MoviesContainer/MoviesContainer.js

The Movie and MoviesContainer components now have their basic boilerplates and are linked up to App.

Movie components

---

src/containers/UserForm/UserForm.js

Okay I made this branch late from Nav so I needed to add this one, had some minor conflicts in that process, but they are all resolved now.

User form setup

---

src/components/App.js
src/containers/Movie/Movie.js
src/containers/MoviesContainer/MoviesContainer.js

Movie state

---

src/index.js

Connected Store. Checked in app. Store in redux tools. Fixed some directory names and file paths.

Add store successfully

---

public/index.html
src/components/App.js
src/index.js
src/reducers/index.js

Add movies to store by refactoring with redux

---

src/actions/index.js
src/components/App.js
src/containers/MoviesContainer/MoviesContainer.js
src/index.js
src/reducers/errorMessage.js
src/reducers/index.js
src/reducers/loading.js

Error message is in store! And also popping up on the DOM if api url is incorrect.

Add error handling to store

---

src/components/App.js
src/containers/Nav/Nav.css
src/containers/Nav/Nav.js
src/index.js

Successfully added in the router path for /login . This also links to this when the login button is clicked. Had to change HashRouter back to BrowserRouter for now.

Route login

---

src/containers/Movie/Movie.css
src/containers/Movie/Movie.js

Favorite star is added to the movie and movie structure was reworked slightly.

Styling two

---

src/containers/Movie/Movie.test.js
src/containers/Movie/__snapshots__/Movie.test.js.snap

Add movie test

---

src/actions/index.js
src/containers/SignUpForm/SignUpForm.js
src/reducers/currentUser.js
src/reducers/index.js
src/utils/apiCalls.js

We are now saving user to store. Paired with @jmevans0211 on this. Also adding another error to catch if there is a 404 error.

Save user to store

---

src/containers/Movie/Movie.css
src/containers/Nav/Nav.css
src/containers/Nav/Nav.js
src/reducers/currentUser.js

Here is a PR for this ticket: Once user is signed in, display user name // conditionally render the nav ^ and display log out #15
Checkout the nav.js file, here is were I did the rendering. Lots of repetition, but it works, so would love to get some feedback on how I could write this in a cleaner fashion if there is one!
I also changed the default state of currentUser in the reducer to 'null' so I could use that as a falsey statement in my conditionals.
I also moved the star on the movies up a pinch b/c there was a sliver of white between the star and the bottom of the movie poster that was driving me nuts.

Nav render

---

src/containers/LoginForm/LoginForm.js
src/containers/Movie/Movie.js
src/containers/SignUpForm/SignUpForm.css
src/containers/SignUpForm/SignUpForm.js

So with this pr, I would almost love for both of you to log on to this branch and try to break it. 
Let me know what you think. This PR accounts for if an input is left empty. You will see async and await in a seemingly strange place but because this.setState is technically asynchronous  it would not work with out this.

Form no input catch

---

src/containers/LoginForm/LoginForm.css
src/containers/LoginForm/LoginForm.js
src/containers/SignUpForm/SignUpForm.css
src/containers/SignUpForm/SignUpForm.js

So this branch adds ability for a user to sign up if they do not have an account from the login page and vise versa.
I cold not get the error message not to affect the sizing and placement of the text below it, depending on window size I feel the placement of the form can get a tiny bit squirelly vertically, -- @qfarenwald this might be a good place for the code snippet you shared, I was just not a 100% sure where to put it. 
The only thing -- May be an Icebox thing -- I was thinking was like the movie tracker logo on both forms and maybe a welcome back on the login page, I fear that is me being to perfectionist though, and I really just need to finish the test for login ( not signup) and move on. 
Appreciate thoughts and feedback. Oh this also add a hover state of gold to the buttons.

Add links in form

---

src/actions/index.js
src/components/App.js
src/containers/LoginForm/LoginForm.js
src/containers/Nav/Nav.js
src/reducers/currentUser.js

This PR allows us to logout! A new action was created to resent the user in store to null, and allowing the conditional rendering of the nav and the routes to kick in.

Nav render two

---

src/components/App.js
src/containers/Movie/Movie.js
src/containers/MoviesContainer/MoviesContainer.js
src/containers/Nav/Nav.js
src/utils/helpers.js

Get favorite

---

src/actions/actions.test.js
src/containers/SignUpForm/SignUpForm.js
src/containers/SignUpForm/SignUpForm.test.js
src/containers/SignUpForm/__snapshots__/SignUpForm.test.js.snap

Just some actions tests and passing signup tests!

Action test je

---

src/containers/LoginForm/LoginForm.css
src/containers/Movie/Movie.css
src/containers/MoviesContainer/MoviesContainer.css
src/containers/SignUpForm/SignUpForm.css
src/containers/SignUpForm/SignUpForm.js
src/images/MovieTracker_star_fav.svg
src/reducers/currentUser.js

Did some of the styling tweaks we talked about... vertically centered both forms and made their heights adaptable based on the content within. On the movies container, i got the top of the movies to not be cut off when you hover over them. I also played with some styling and placement here. If you dont like anything, like the missing white border, i can certainly go back to that very easily.
The movies container still does not auto center vertically. Would still need to figure that out.
Also made a gold star image for when we toggle the favorites.

Styling three

---

src/actions/index.js
src/components/App.js
src/components/App.test.js
src/containers/LoginForm/LoginForm.js
src/containers/Movie/Movie.js
src/containers/MoviesContainer/MoviesContainer.js
src/reducers/favorited.js
src/utils/apiCalls.js

- Two new actions using the same reducer with retrieved favorites and new favorites being added to the same array in store. 
- movie deleting from store
- removed `await response` from deleteFavorite as this was unneeded and causing the bug.
All is working, happy to walk through/review

Toggle favorite je

---

src/components/App.js
src/containers/FavoritesContainer/FavoritesContainer.js
src/containers/LoginForm/LoginForm.js
src/containers/Nav/Nav.js

*** 1st PR to Merge ** 
Able to click on Favorites and see your favorites once signed in!

Favorites view

---

src/actions/actions.test.js
src/containers/Movie/Movie.js
src/containers/Movie/__snapshots__/Movie.test.js.snap
src/containers/MoviesContainer/MoviesContainer.test.js
src/containers/MoviesContainer/__snapshots__/MoviesContainer.test.js.snap

1. Got rid of errors in the testing terminal 
2. Got the tests to pass that were related to those errors in Movie/MovieContainer
3. Added describe blocks to acitons.test.js
4. Added the saveMovie action test

Action tests

---

src/containers/LoginForm/LoginForm.js
src/containers/LoginForm/LoginForm.test.js

Last attempt at getting the login form tests out of the 'red'. So. Close.

Login form test
